language: node_js
node_js:
- lts/*
script:
- echo "n/a"
deploy:
- provider: script
  skip_cleanup: true
  script:
  - npx @dhis2/cli-utils release --publish npm
  on:
    tags: false
    branch: master
env:
  global:
  - GIT_AUTHOR_NAME=@dhis2-bot
  - GIT_AUTHOR_EMAIL=apps@dhis2.org
  - GIT_COMMITTER_NAME=@dhis2-bot
  - GIT_COMMITTER_EMAIL=apps@dhis2.org
  - secure: hxLZsdXhfv6hfWxktM7MYWov65oMjT7lRi99j57RcnFku8uGyZPZFiy4UsLafwEGC5+lLjSuYsmQ3c0lsTERiYK/oyhyzHlkQdYHxhNddqg0EZSAqhLfKtRBkBpPuTQYVBJW/VQ3/7vFCtjd8yVxbzDOZB59UQleZWPU+c9X18KJuOIg9PXa+KNlxLNgH8CdnxJT6GJ2vq0vv7TQKpPv8dEV9/UOMmdub7fMkbe76BDPOGAO2pdEFGbkuqMav5QAmpmYmxOCI5Ed7FKsc7emfRIPGQiT4u2p2WwJzwsmP++Z1P5Zj6iL6PU7tdoSu9XfRmVTAK3dSd/IAcP2nIaPh5TogMKD3dNrrLOoQwsrZ+NCOh5MsGjN4oNbXwwB+0YIFug/+eUzwsRDec8b7lZ9MTaRTHUlFC6NBTz/uCg2ROXMWnGKgIIzH9+EF0pByZwAknJ0QMjEiOuoQs28FOafcuRZJA2XnKCpKJAizduv3tJeHz0MgU7pytwJtt6rR9gcq9FVZDPU5nP/JP0wpErZwm8XIwBnUXzwDlTnL3x3Ib6ESUpTZZ9jdIy5CXwSE8sUpmgU/t7V7FkMGWEl6+wrGbkqu3CxMr7lpitIfpGX2+F5eR5eK0tbS/8vXQPLbaSNCn5pYG4kHhDXzablFWSvGNYRzHcm4hU3LkwC36jv29U=
  - secure: iqWj9Um1lFgBJNABDh/SlRc9psZyuSAlrVXmljT+O8WOJ7r7wT4m5ep2VWYTdO+0W1WzFIUNePPdHaE29ode2LqhkgwYyQajpOmhxvigys7Q1cqxFOsWceqiKADgLP+UF0INTlwh4CpwZArAwb6uYl6qfQRub+9eu+98HFbRbzcNZTPkjKyGfasAgkaqDeCVnzVoMWFSqQP913DmbU+58jGRIgYZlso77Y8kUBwWh48FMbiEopxCvm5IzduSXRe+5wzcxOrAHSUsHSNxIU9qA3sQWIw960Gfea9lpFfdhkkOtV6XUHrcotgWYcwfrEm2OtrB9SrAwXnRwYd9Vzn3yw/uU/FF0OgbeKW3j8S2Mi16Ltreueb5XlIBA11dEHMkouc66xSPBfTHshkmOpi8EilWQjRPjoCDauZ44Rxt1k5cghcIwqAqzFL1x+NJE7BhqA4f9VFfMgNDmRa2q86jYgveNkNjz1cuBdcrcdO/wzDdPiwRwe6qvISiWr2GwkoKpBnnktWMmIuEDiuPHR8VrTg6t699hfy47UVE0XNaE5VUANtpwg0lDUkCiU+2ylpeWL9rkdxLP1hTo8N6Zw8pAOM3dZtb0OKGcrbFmtoWUbWWERo7JBxk5sowjBy7WOQukwJfhS+pLfsLFzA+fuYi8L/+IMOVRSABCOrRmvvjZwQ=
